language: ruby
bundler_args: --without development
script: bundle exec rspec spec
rvm:
  - ruby-1.9.3
  - ruby-2.0.0
  - ruby-2.1.0
gemfile:
  - gemfiles/mongoid31.gemfile
  - gemfiles/mongoid40.gemfile
services:
  - mongodb
matrix:
  allow_failures:
    - rvm: ruby-head
